const actions = {
  SET_USER_AUTHENTICATED: "SET_USER_AUTHENTICATED",
  SET_USER_DETAILS: "SET_USER_DETAILS",
  SET_TENANT: "SET_TENANT",
  SET_NAVIGATION: "SET_NAVIGATION",
};
export default actions;
