export const {
  REMOVE_ITEM,
  UPDATE_ITEM,
  UPDATE_ITEM_QUANTITY,
  ADD_UPDATE_ITEM,
  ADD_UPDATE_SPECIAL_ITEM,
  UPDATE_SPECIAL_ITEM_QUANTITY,
  REMOVE_SPECIAL_ITEM,
  ADD_VOUCHER,
  REMOVE_VOUCHER,
  SET_VOUCHER_SELECTION,
  ADD_VOUCHER_ITEM,
  CLEAR_VOUCHER_SELECTION,
  SET_MENU,
  ADD_ITEM_COMMENT,
  CUSTOMIZE_ITEM,
  CUSTOMIZE_VOUCHER_ITEM,
  CUSTOMIZE_CUSTOM_ITEM,
  ADD_CUSTOMIZED_ITEM,
  ADD_CUSTOMIZED_VOUCHER_ITEM,
  REMOVE_OPTION,
  CANCEL_VOUCHER_SELECTION,
  SET_COMPENSATION,
  SET_DISCOUNT,
  SET_TIP,
  REMOVE_TIP,
  UPDATE_CUTLERY_QUANTITY,
  SET_EDIT_ORDER_DATA,
  SET_ACTIVE_CATEGORY_TAB,
} = {
  UPDATE_ITEM: "update-item",
  UPDATE_ITEM_QUANTITY: "update-item-quantity",
  REMOVE_ITEM: "remove-item",
  ADD_UPDATE_ITEM: "add-update-item",
  ADD_UPDATE_SPECIAL_ITEM: "add-update-special-item",
  UPDATE_SPECIAL_ITEM_QUANTITY: "update-special-item-quantity",
  REMOVE_SPECIAL_ITEM: "remove-special-item",
  ADD_VOUCHER: "add-voucher",
  REMOVE_VOUCHER: "remove-voucher",
  SET_VOUCHER_SELECTION: "set-voucher-selection",
  ADD_VOUCHER_ITEM: "add-voucher-item",
  CLEAR_VOUCHER_SELECTION: "clear-voucher-selection",
  SET_MENU: "set-menu",
  ADD_ITEM_COMMENT: "add-item-comment",
  CUSTOMIZE_ITEM: "customize-item",
  CUSTOMIZE_VOUCHER_ITEM: "customize-voucher-item",
  CUSTOMIZE_CUSTOM_ITEM: "customize-custom-item",
  ADD_CUSTOMIZED_ITEM: "add-customized-item",
  ADD_CUSTOMIZED_VOUCHER_ITEM: "add-customized-voucher-item",
  REMOVE_OPTION: "remove-option",
  CANCEL_VOUCHER_SELECTION: "cancel-voucher-selection",
  SET_COMPENSATION: "set-compensation",
  SET_DISCOUNT: "set-discount",
  SET_TIP: "set-tip",
  REMOVE_TIP: "remove-tip",
  UPDATE_CUTLERY_QUANTITY: "update-cutlery-quantity",
  SET_EDIT_ORDER_DATA: "set-edit-order-data",
  SET_ACTIVE_CATEGORY_TAB: "set-active-category-tab",
};
